server:
  port: 8066
spring:
  jackson:
    time-zone: GMT+8
  profiles:
    active: dev
  application:
    name: SmartCloud
  redis:
    host: 127.0.0.1
    port: 6379
  cache:
    #ehcache配置文件路径
    ehcache:
      config: classpath:/ehcache/ehcache.xml
    #指定缓存类型，可加可不加
    #type: ehcache
  datasource:
    # 数据库驱动：
    druid:
      url: jdbc:mysql://127.0.0.1:3306/smartcloud?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&serverTimezone=UTC
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      max-active: 30
      min-idle: 5
      max-wait: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      filters: stat,wall
      use-global-data-source-stat: true
      webStatFilter:
        enabled: true
        statViewServlet:
          enabled: true
          # 设置白名单，不填则允许所有访问
          allow:
          url-pattern: /monitor/druid/*
        filter:
          stat:
            enabled: true
            # 慢SQL记录
            log-slow-sql: true
            slow-sql-millis: 1000
            merge-sql: true
          wall:
            config:
              multi-statement-allow: true
    # ums core
  ums:
    one-click-login:
      enable: false
      # ================ 第三方授权登录相关配置 ================
      oauth:
        # 是否支持第三方授权登录功能, 默认: true
        enabled: true
        # 抑制反射警告, 支持 JDK11, 默认: false , 在确认 WARNING: An illegal reflective access operation has occurred 安全后, 可以打开此设置, 可以抑制反射警告.
        suppress-reflect-warning: true
        # 第三方服务商: providerId, 支持所有 JustAuth 支持的第三方授权登录, 目前有 32 家第三方授权登录
        # 第三方登录授权登录 url 前缀, 不包含 ServletContextPath，默认为 /auth2/authorization.
        auth-login-url-prefix: /auth2/authorization
        # 第三方登录回调处理 url 前缀 ，也就是 RedirectUrl 的前缀, 不包含 ServletContextPath，默认为 /auth2/login.
        redirect-url-prefix: /auth2/login
        # 第三方登录回调的域名, 例如：http://localhost:9090 默认为 "http://127.0.0.1"，
        # redirectUrl 直接由 {domain}/{servletContextPath}/{redirectUrlPrefix}/{providerId}(ums.oauth.[qq/gitee/weibo])组成
        domain: http://localhost:${server.port}
        # 第三方授权登录成功后的默认权限, 多个权限用逗号分开, 默认为: "ROLE_USER"
        default-authorities: ROLE_USER
        # 用于 JustAuth 的代理(HttpClient)设置
        proxy:
          # 用于国内代理(HttpClient)超时, 默认 PT3S
          timeout: PT3S
          # 用于国外网站代理(HttpClient)超时, 默认 PT15S
          foreign-timeout: PT150S

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: www.bwsensing.com.gatewayimpl.database.dataobject

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

alibaba :
  cloud :
    # 密钥 ID
    access-key : ............
    # 密钥  secret
    secret-key : ..............
    mail:
      regionId : cn-hangzhou
      host : dm.aliyuncs.com
      version : 2015-11-23

system:
  visualization:
    decimal: 3
  alert:
    prefix: http://
    server-host: 127.0.0.1
    port: 8100
    forward: 1h
  encrypt:
    key: TE53DAH...9VMHEP
    vector: ZEM8........EJDHMKG0
  token:
    secret: ..........
    iss: ........
    exist_time: 8
    head: Authorization
    prefix: Bearer
  notification:
    max_last: 30
    prefix: NOTIFICATION_
  netty:
    port: 9876
    read_timeout: 4
    wait_timeout: 0
    all_timeout: 8
  udp:
    port: 9875


